### PR TITLE
Change all line endings to unix

### PR DESCRIPTION
**Pull request by mankeli**
How about something like this? All text-files (except MegaWizard PLL's) converted to Unix line endings for consistency.

Quartus seems to be fine with it. I only tested on Linux though, so idk  if the Windows version changes these back to CRLFs.

### CODE REVIEW

**Comment by sorgelig** [comment]
Main development platform is Windows.

**Comment by mankeli** [comment]
So? Half of the files have unix line endings anyway. This would just fix them to be consistent across the files.

**Comment by sorgelig** [comment]
Quartus doesn't really care about line endings. Git also doesn't care being set properly.

**Comment by mankeli** [comment]
fair enough

**Pull request closed without merging**
