### PR TITLE
Fix potential errors in #18.

### PR DESCRIPTION
**Pull request by bellwood420**
- Fix `read` signal was asserted during read terminating stage since it is illegal to Avalon-MM spec.
- Fix multiple read request was not considered.
- Separate write/read handling logic to simplify.

### CODE REVIEW

**Comment by sorgelig** [comment]
type d without size has no meaning as size is 32 bit in this case.
so ```'d1``` has the same meaning as ```32'd1``` and then you get the warning of destination narrower than source.
If you want to make code accepting different width the consider following things:
- Direct unconditional assignment (including default values) doesn't require width specifier. So following gets compiled without warnings: ```reg [7:0] myreg = 0;```
- conditional assignment require width specifier but happily accepts lower width (extended by 0 when assigned), so this is correct: ```wire [7:0] mywire = flag ? 1'b1 : 1'b0;```
- Compare doesn't require width specifier.
- ```'dX``` as mentioned above has no meaning as it equals simple ```X``` with width 32bits.

**Comment by bellwood420** [comment]
@sorgelig 

Thanks! I learned a lot :)

I fixed to suppress warning messages.
I've been on testing to ensure, but it already merged.
Shall I open another PR?

**Comment by sorgelig** [comment]
i've fixed it already :)
I've also reduced number of parameters as 2 of them can be calculated.

**Comment by bellwood420** [comment]
I didn't notice that. Thanks a lot!

**Pull request merged**
