### PR TITLE
vga_out: relax timings

### PR DESCRIPTION
**Pull request by paulb-nl**

### CODE REVIEW

**Comment by paulb-nl** [comment]
@sorgelig I forgot that vga_out should use the hdmi clock when the scaler is enabled so vga_scaler=1 doesn't work properly now. It needs two different clocks. It is probably best to revert it.

**Comment by sorgelig** [comment]
This is a very bad news.. A lot of cores have been updated already!
That's why i don't like to accept PR for framework. It should be tested in many different scenarios. I'm doing all relevant tests when i provide update in framework. So i was in impression other devs do the same before submit PR..

**Comment by jotego** [comment]
Maybe you could require a small check list for future pull requests. Add it to the wiki here, maybe.

**Comment by sorgelig** [comment]
clock selector probably could be added but i think it won't relax the timings.. 
Will think.. probably need to revert back to combinatorial logic.

**Comment by paulb-nl** [comment]
Do you think 2 separate `vga_out` instances for vga scaler on and off is ok? The combinatorial logic creates artifacts on YPbPr output. See red lines in below picture. With the new timing there are no artifacts even up to 1080p. I have tested with scaler on and off.

grayramp_scaler

**Comment by sorgelig** [comment]
i see.. yes, 2 instances may work too.. 
i will work on it.

**Comment by sorgelig** [comment]
@paulb-nl i've pushed the changes. Please test ypbpr mode in vga_scaler enabled and disabled mode.

**Comment by paulb-nl** [comment]
I have tested your changes with rgb, ypbpr, vga_scaler 0 & 1, composite_sync 0 & 1. Everything works well.

**Pull request merged**
