### PR TITLE
Flip without rotation

### PR DESCRIPTION
**Pull request by jotego**
This is a small thing for saving power and freeing the DDR when not needed.
I separate this line from the flip PR I'm preparing just in case you don't like this one.

### CODE REVIEW

**Comment by jotego** [comment]
Added the flip feature. If rotation is disabled but flip is set, then the image is flipped. This is useful when image flipping cannot be done at the core level.

**Comment by birdybro** [comment]
@jotego I'm learning how to port a core, but I've been running into the same issue I ran into with cores that had any kind of rotation that I was attempting to update the sys for.

image

I've narrowed it down to likely being the changes in this PR. Do you have any advice for me? I've spent a few days trying to make it work and it still won't work. Previously when trying to update the framework in older arcade cores with screen rotation, again I spent days on it and got nowhere.

Any advice would be appreciated, thank you. :)

**Comment by jotego** [comment]
My advise is to stop using the .* syntax for connecting modules. You seem to be getting a lot of errors related to that.

**Comment by birdybro** [comment]
That's a good point, however I would have to then disconnect the FB_* ports entirely, and this doesn't seem to be necessary until after the framework was updated in the last 4 months. I don't believe the framebuffer being disabled will allow the screen to rotate.

https://github.com/MiSTer-devel/Template_MiSTer/blob/a9d79e25b18ae60db3e9aaaa1fb60bf65388b61f/sys/arcade_video.v#L283

Am I reading that right?

**Comment by birdybro** [comment]
#set_global_assignment -name VERILOG_MACRO "MISTER_FB=1"

My mistake... WOW. I didn't see that this line was commented in the QSF. Lack of syntax highlighting + ADHD.

Thanks @jotego! :D

**Comment by jotego** [comment]
I'm glad it worked out for you in the end.

**Pull request merged**
